name = "pastebin-worker"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

account_id = "6605e69d09208b14b29c196be44dec5a"
main = "src/index.ts"
workers_dev = false

[vars]
ENVIRONMENT = "production"
BASE_URL = "https://pastebin.sphenhe.me"

[site]
bucket = "./static/dist"

[[routes]]
pattern = "pastebin.sphenhe.me"
custom_domain = true

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'pastebins'

[[d1_databases]]
binding = "DB"
database_name = "pastebins"
database_id = "e7d77803-c383-45c8-9481-c1630aa43bca"
