name= "pastebin-worker"
compatibility_date = "2023-10-30"
account_id= "6605e69d09208b14b29c196be44dec5a"
main = "src/index.ts"
workers_dev = false

# 如果没使用自定义域名，将BASE_URL改为 worker 的默认路由
vars = { ENVIRONMENT = "production", BASE_URL = "https://pastebin.sphenhe.me" }

# 如果不使用自定义域名，将下面的代码注释掉
route = { pattern = "pastebin.sphenhe.me", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "4d50ab8ff259400f82c5938315e8acd8" },
]

[site]
bucket = "./static/dist"


[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'pastes'
